### ISSUE TITLE
Question: Providing `helpers` to html task

### ISSUE THREAD

**Issue by lyzadanger** [cloudfour/core-gulp-tasks#10]
In the scenario where a site project has our forthcoming common Handlebars helpers module as a dependency _and_ opted in to the `html` task from this repo, what is the mechanism for providing those common helpers to the `html` task so it can make use of them when compiling templates?

(i.e. Should this be in the `gulp` config object passed to the task, and how?)

**Comment by erikjung** [comment]
@lyzadanger If I'm understanding the question correctly...

```js
/* site project gulpfile.js */

var gulp = require('gulp');
var tasks = require('core-gulp-tasks');

tasks.html(gulp, {
  plugins: {
    handlebars: {
      helpers: require('core-hbs-helpers')
    }
  }
});
```

**Comment by erikjung** [comment]
Or, if the project uses a master config for all tasks: 

```js
/* tasks.config.js */

module.exports = {
  'html': {
    plugins: {
      handlebars: {
        helpers: require('core-hbs-helpers')
      }
    }
  }
};
```
```js
/* site project gulpfile.js */

var config = require('./tasks.config');
var gulp = require('gulp');
var tasks = require('core-gulp-tasks');

tasks.html(gulp, config.html);
```

**Comment by lyzadanger** [comment]
You answered my question...`html` task takes a `plugin` property. There's a `handlebars` object with `helpers` pointing at the needed `npm` module. Thanks! I'm going to leave this open for a bit until we have that helpers repo that I can point at.

**Comment by erikjung** [comment]
It would probably be nice to include a comment near the task `defaults` with a URL pointing to the `gulp-compile-handlebars` option docs.

**Comment by erikjung** [comment]
@lyzadanger FYI, the helpers repo now exists: https://github.com/cloudfour/core-hbs-helpers

**Comment by erikjung** [comment]
Assuming this can be closed.
