### ISSUE TITLE
Re-write assets, clean, css tasks in ES6

### ISSUE THREAD

**Issue by lyzadanger** [cloudfour/core-gulp-tasks#20]
Please (branch and PR) convert 

[assets.js](https://github.com/cloudfour/core-gulp-tasks/blob/09c3cba268b1f216b5112f7eadfd05265385abe1/lib/assets.js), [clean.js](https://github.com/cloudfour/core-gulp-tasks/blob/09c3cba268b1f216b5112f7eadfd05265385abe1/lib/clean.js) and [css.js](https://github.com/cloudfour/core-gulp-tasks/blob/09c3cba268b1f216b5112f7eadfd05265385abe1/lib/css.js) to ES6. 

Don't forget to make sure tests still pass! Let me know if you need any help.

**Comment by lyzadanger** [comment]
@mrgerardorodriguez After #33 gets merged, you can resume wrapping this up. We're not using babel anymore, so make sure to reference https://kangax.github.io/compat-table/es6/#node4 for ES6 feature support in our version of node.

Much of what we've been doing so far is supported. The only thing that broke specifically yesterday was object destructuring, which was in my refactoring of the `html` task.

**Comment by lyzadanger** [comment]
Oh, and you should _definitely_ merge `master` into your working branch after #33 merges as, e.g., node versions have changed and the `gulpfile` in the test directory has been renamed.

**Comment by mrgerardorodriguez** [comment]
Will do, thanks @lyzadanger!
