### ISSUE TITLE
Rewrite js, serve, watch tasks in ES6

### ISSUE THREAD

**Issue by lyzadanger** [cloudfour/core-gulp-tasks#22]
Please rewrite [js.js](https://github.com/cloudfour/core-gulp-tasks/blob/09c3cba268b1f216b5112f7eadfd05265385abe1/lib/js.js), [serve.js](https://github.com/cloudfour/core-gulp-tasks/blob/09c3cba268b1f216b5112f7eadfd05265385abe1/lib/serve.js) and [watch.js](https://github.com/cloudfour/core-gulp-tasks/blob/09c3cba268b1f216b5112f7eadfd05265385abe1/lib/watch.js) in ES6.

Make sure tests still pass!

**Comment by erikjung** [comment]
@lyzadanger I wanted to mention a possible caveat to doing this. I'm not sure `requireDir` (in the [index.js](https://github.com/cloudfour/core-gulp-tasks/blob/master/lib/index.js) file) will work nicely with `export default` within the task modules. We might need to leave the `module.exports` in place for each task.

OR we could not use `requireDir` at all, and simply use `export` in the index file for each task:

```js
export {default as css} from './css';
export {default as html} from './html';
// ..
```
