### ISSUE TITLE
Log webpack warnings

### ISSUE THREAD

**Issue by erikjung** [cloudfour/core-gulp-tasks#34]
A good recommendation came from @tylersticka:

Add something similar to

``` js
if (stats.hasWarnings()) {
  utils.log(stats.toString())
}
```

inside of this function: https://github.com/cloudfour/core-gulp-tasks/blob/master/lib/js.js#L35-L38

See: https://github.com/webpack/docs/wiki/node.js-api#stats

**Comment by tylersticka** [comment]
Don't forget `stats.hasErrors()`, too. :smile:
