### ISSUE TITLE
Tests should exist

### ISSUE THREAD

**Issue by erikjung** [cloudfour/core-gulp-tasks#5]
Open to ideas on how to maintain tests for these tasks.

**Comment by lyzadanger** [comment]
For the generator piece, I may follow the pattern seen here https://github.com/yeoman/generator-gulp-webapp/tree/master/test

(`mocha` invoked by `npm test`)

If that's in any way helpful to you...

**Comment by erikjung** [comment]
Tests have been added via #11.
