### ISSUE TITLE
Consider making browserSync reload glob broader

### ISSUE THREAD

**Issue by lyzadanger** [cloudfour/core-gulp-tasks#6]
Right now https://github.com/cloudfour/core-gulp-tasks/blob/master/lib/serve.js#L9

will do a reload if `html`, `js`, `css` changes. I feel like making this broader might be to our advantage—for images, other assets, e.g.

**Comment by erikjung** [comment]
@lyzadanger I agree. We could default to `**/*`.

**Comment by erikjung** [comment]
Closed via #8.
